import { writeFileSync } from 'fs';

const crlf = '\r\n';

const lines = [];

lines.push('/**');
lines.push(' * AUTH-1/AUTH-2: Supabase JWT issuer + algorithm hardening tests.');
lines.push(' *');
lines.push(' * Tests verify-jwt.ts hardening directly (no HTTP layer).');
lines.push(' * ES256 tokens generated with jose.generateKeyPair. HS256 tokens use the');
lines.push(' * SUPABASE_JWT_SECRET from vitest env (supplied in vitest.config.ts).');
lines.push(' * No production secrets are hardcoded or printed.');
lines.push(' */');
lines.push("import { describe, it, expect, beforeAll } from 'vitest';");
lines.push("import { generateKeyPair, SignJWT } from 'jose';");
lines.push("import { verifySupabaseJwt } from '../../src/lib/auth/verify-jwt.js';");
lines.push("import { tokenWithIssuer, expiredToken } from '../../test/helpers/tokens.js';");
lines.push("import request from 'supertest';");
lines.push("import type { Express } from 'express';");
lines.push("import { vi } from 'vitest';");
lines.push('');
lines.push("const EXPECTED_ISSUER = (process.env.SUPABASE_URL ?? 'https://test.supabase.co').replace(/\\/+$/, '') + '/auth/v1';");
lines.push("const WRONG_ISSUER = 'https://evil.supabase.co/auth/v1';");
lines.push("const FOREIGN_ISSUER = 'https://other.supabase.co/auth/v1';");
lines.push('');
lines.push('let es256PrivateKey;');
lines.push('');
lines.push('async function signEs256(payload, iss) {');
lines.push(' return new SignJWT(payload)');
lines.push(' .setProtectedHeader({ alg: "ES256", typ: "JWT" })');
lines.push(' .setIssuer(iss ?? EXPECTED_ISSUER)');
lines.push(' .setExpirationTime("1h")');
lines.push(' .sign(es256PrivateKey);');
lines.push('}');
lines.push('');
lines.push('async function signRs256(payload) {');
lines.push(' const { privateKey } = await generateKeyPair("RS256");');
lines.push(' return new SignJWT(payload)');
lines.push(' .setProtectedHeader({ alg: "RS256", typ: "JWT" })');
lines.push(' .setIssuer(EXPECTED_ISSUER)');
lines.push(' .setExpirationTime("1h")');
lines.push(' .sign(privateKey);');
lines.push('}');
lines.push('');
lines.push('beforeAll(async () => {');
lines.push(' const keys = await generateKeyPair("ES256");');
lines.push(' es256PrivateKey = keys.privateKey;');
lines.push('});');
lines.push('');
lines.push('describe("AUTH-1/AUTH-2: verifySupabaseJwt hardening", () => {');
lines.push('');
lines.push(' it("accepts a valid ES256 JWT from the expected issuer", async () => {');
lines.push(' const token = await signEs256({ sub: "user-1", network_id: "net-1", kind: "operator", role: "admin", app_metadata: { role: "admin" } });');
lines.push(' const payload = await verifySupabaseJwt(token);');
lines.push(' expect(payload.sub).toBe("user-1");');
lines.push(' expect(String((payload as any)["network_id"] ?? "")).toBe("net-1");');
lines.push(' });');
lines.push('');
lines.push(' it("rejects an ES256 JWT with wrong issuer", async () => {');
lines.push(' const token = await signEs256({ sub: "u1", kind: "operator" }, WRONG_ISSUER);');
lines.push(' await expect(verifySupabaseJwt(token)).rejects.toThrow();');
lines.push(' });');
lines.push('');
lines.push(' it("rejects an ES256 JWT with foreign-project issuer", async () => {');
lines.push(' const token = await signEs256({ sub: "u1", kind: "operator" }, FOREIGN_ISSUER);');
lines.push(' await expect(verifySupabaseJwt(token)).rejects.toThrow();');
lines.push(' });');
lines.push('');
lines.push(' it("rejects an ES256 JWT with no issuer claim", async () => {');
lines.push(' const token = await new SignJWT({ sub: "u1", kind: "operator" })');
lines.push(' .setProtectedHeader({ alg: "ES256", typ: "JWT" })');
lines.push(' .setExpirationTime("1h")');
lines.push(' .sign(es256PrivateKey);');
lines.push(' await expect(verifySupabaseJwt(token)).rejects.toThrow();');
lines.push(' });');
lines.push('');
lines.push(' it("rejects an RS256-signed JWT (algorithm confusion blocked)", async () => {');
lines.push(' const token = await signRs256({ sub: "u1", kind: "operator" });');
lines.push(' await expect(verifySupabaseJwt(token)).rejects.toThrow();');
lines.push(' });');
lines.push('');
lines.push(' it("rejects an expired ES256 JWT", async () => {');
lines.push(' const expired = await new SignJWT({ sub: "u1", kind: "operator" })');
lines.push(' .setProtectedHeader({ alg: "ES256", typ: "JWT" })');
lines.push(' .setIssuer(EXPECTED_ISSUER)');
lines.push(' .setExpirationTime("-1h")');
lines.push(' .sign(es256PrivateKey);');
lines.push(' await expect(verifySupabaseJwt(expired)).rejects.toThrow();');
lines.push(' });');
lines.push('');
lines.push(' it("rejects a malformed JWT string", async () => {');
lines.push(' await expect(verifySupabaseJwt("not.a.valid.jwt.token.at.all")).rejects.toThrow();');
lines.push(' });');
lines.push('');
lines.push(' it("token from a foreign Supabase project (wrong issuer) is rejected", async () => {');
lines.push(' const token = await signEs256({ sub: "u1", kind: "operator" }, FOREIGN_ISSUER);');
lines.push(' await expect(verifySupabaseJwt(token)).rejects.toThrow();');
lines.push(' });');
lines.push('');
lines.push(' it("HS256 test-path preserves valid app_metadata claims (kind, role)", async () => {');
lines.push(' const token = tokenWithIssuer({ kind: "operator", role: "admin", network_id: "net-1" });');
lines.push(' const payload = await verifySupabaseJwt(token);');
lines.push(' expect((payload as any)["sub"]).toBeDefined();');
lines.push(' expect(String((payload as any)["network_id"] ?? "")).toBe("net-1");');
lines.push(' const appMeta = (payload as any)["app_metadata"];');
lines.push(' expect(appMeta?.["role"]).toBe("admin");');
lines.push(' });');
lines.push('');
lines.push(' it("HS256 test-path preserves portal claims (advertiser kind, owner_id)", async () => {');
lines.push(' const { portalToken } = await import("../../test/helpers/tokens.js");');
lines.push(' const token = portalToken({ userId: "u-2", networkId: "net-2", kind: "advertiser", ownerId: "adv-1" });');
lines.push(' const payload = await verifySupabaseJwt(token);');
lines.push(' expect(String((payload as any)["network_id"] ?? "")).toBe("net-2");');
lines.push(' const appMeta = (payload as any)["app_metadata"];');
lines.push(' expect(appMeta?.["kind"]).toBe("advertiser");');
lines.push(' });');
lines.push('');
lines.push(' it("HS256 test-path rejects wrong issuer", async () => {');
lines.push(' const token = tokenWithIssuer({ iss: WRONG_ISSUER, kind: "operator" });');
lines.push(' await expect(verifySupabaseJwt(token)).rejects.toThrow();');
lines.push(' });');
lines.push('');
lines.push(' it("HS256 test-path rejects expired tokens", async () => {');
lines.push(' const token = expiredToken();');
lines.push(' await expect(verifySupabaseJwt(token)).rejects.toThrow();');
lines.push(' });');
lines.push('');
lines.push(' it("platform-admin auth unaffected (separate module, separate secret)", async () => {');
lines.push(' const { signPlatformAdminToken, verifyPlatformAdminToken } = await import("../../src/lib/auth/platform-admin-token.js");');
lines.push(' const token = await signPlatformAdminToken("admin-1");');
lines.push(' const payload = await verifyPlatformAdminToken(token);');
lines.push(' expect(payload.pa_sub).toBe("admin-1");');
lines.push(' expect(payload.kind).toBe("platform_admin");');
lines.push(' });');
lines.push('});');
lines.push('');
lines.push('describe("AUTH-1: dashboard auth end-to-end (mocked app)", () => {');
lines.push(' let app;');
lines.push('');
lines.push(' it("valid dashboard token with correct issuer passes dashboardAuth", async () => {');
lines.push(' vi.resetModules();');
lines.push(' vi.doMock("../../src/lib/db/pool.js", () => ({');
lines.push(' pool: { connect: async () => ({ query: async () => ({ rows: [], rowCount: 0 }), release: () => {} }) },');
lines.push(' query: async () => ({ rows: [], rowCount: 0 }),');
lines.push(' }));');
lines.push(' const { buildDashboardApp } = await import("../../src/surfaces/dashboard/app.js");');
lines.push(' app = buildDashboardApp();');
lines.push(' const { SignJWT } = await import("jose");');
lines.push(' const secret = new TextEncoder().encode(process.env.SUPABASE_JWT_SECRET ?? "test-jwt-secret-do-not-use-in-prod");');
lines.push(' const token = await new SignJWT({ sub: "user-1", network_id: "net-1", kind: "admin", role: "admin", app_metadata: { role: "admin" } })');
lines.push(' .setProtectedHeader({ alg: "HS256", typ: "JWT" })');
lines.push(' .setIssuer(EXPECTED_ISSUER)');
lines.push(' .setExpirationTime("1h")');
lines.push(' .sign(secret);');
lines.push(' const res = await request(app)');
lines.push(' .get("/api/v1/network/offers")');
lines.push(' .set("Authorization", "Bearer " + token);');
lines.push(' expect(res.status).not.toBe(200);');
lines.push(' });');
lines.push('');
lines.push(' it("wrong-issuer dashboard token yields 401", async () => {');
lines.push(' vi.resetModules();');
lines.push(' vi.doMock("../../src/lib/db/pool.js", () => ({');
lines.push(' pool: { connect: async () => ({ query: async () => ({ rows: [], rowCount: 0 }), release: () => {} }) },');
lines.push(' query: async () => ({ rows: [], rowCount: 0 }),');
lines.push(' }));');
lines.push(' const { buildDashboardApp } = await import("../../src/surfaces/dashboard/app.js");');
lines.push(' app = buildDashboardApp();');
lines.push(' const { SignJWT } = await import("jose");');
lines.push(' const secret = new TextEncoder().encode(process.env.SUPABASE_JWT_SECRET ?? "test-jwt-secret-do-not-use-in-prod");');
lines.push(' const wrongIssToken = await new SignJWT({ sub: "u1", network_id: "n1", kind: "admin", role: "admin" })');
lines.push(' .setProtectedHeader({ alg: "HS256", typ: "JWT" })');
lines.push(' .setIssuer(WRONG_ISSUER)');
lines.push(' .setExpirationTime("1h")');
lines.push(' .sign(secret);');
lines.push(' const res = await request(app)');
lines.push(' .get("/api/v1/network/offers")');
lines.push(' .set("Authorization", "Bearer " + wrongIssToken);');
lines.push(' expect(res.status).toBe(401);');
lines.push(' });');
lines.push('});');

const content = lines.join(crlf);
writeFileSync('test/isolation/verify-jwt-hardening.test.ts', content + crlf);
console.log('Written:', Buffer.byteLength(content + crlf), 'bytes');
